### PR TITLE
feat: add define command

### PR DESCRIPTION
**Pull request by craftablescience**
image
Taking this literally ;)

I spent about an hour trying to get it to check if the URL is valid, but it seems the only way to reliably do that is to add a dependency, so I didn't do that.

Takes a string input and returns a link to Merriam-Webster, which will have an autogenerated embed if it is a valid URL.

### CODE REVIEW

**Comment by sbrugel** [comment]
Do you have an image of what the resulting embed looks like?

**Comment by sbrugel** [comment]
Looks good. I think for one thing, you should return an error message if the user's inputted string contains more than one word. Additionally, within reasonable limits, is there a way you could check if the word is invalid? i.e. Check if the dictionary page returns a 404 or the like.

**Comment by craftablescience** [comment]
> is there a way you could check if the word is invalid? i.e. Check if the dictionary page returns a 404 or the like.

From the PR description:
> I spent about an hour trying to get it to check if the URL is valid, but it seems the only way to reliably do that is to add a dependency, so I didn't do that.

**Comment by craftablescience** [comment]
> you should return an error message if the user's inputted string contains more than one word
Done

**Review by joshualyon7 — APPROVED** [review]
Looks good to me

**Review by bladetyr — APPROVED** [review]
I'd like to see what it looks like when a 200 error is thrown, but other than that, I think this is good

**Comment by craftablescience** [comment]
It's not an error, it gets a `200 OK` status code for every word you throw into the URL. When a word doesn't exist, it just doesn't generate an embed.

**Review by sbrugel — APPROVED** [review]
@bladetyr a 200 code just means the page/resources loaded fine with no problems.
Approved

**Review by renross — APPROVED** [review]

**Pull request merged**
